import styles from '@/styles/Home.module.css'
import { useQuery, gql } from '@apollo/client';
import { Loading } from '@/components/Loading';
import { Card } from '@/components/Card';
import Head from 'next/head';

export const GET_CATEGORIES = gql`
    query GetCategoryLists{
        categoryList(filters: {}){
            name
            uid
            url_key
            image
        }
    }
`;

export default function Home() {
  const { data, loading, error } = useQuery(GET_CATEGORIES);
  if (loading) {
    return <Loading />;
  }

  if (error) {
    console.error(error);
    return null;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
        {
          data.categoryList.map((cat, i) => (
            <Card key={i} url_key={cat.url_key} image={cat.image} name={cat.name} />
          ))
        }
        </div>
      </main>
    </div>
  )
}
